version: "2"
linters:
  enable:
    - logcheck
  settings:
    custom:
      logcheck:
        path: /home/epas/loglint/loglint/plugin/logcheck.so
        description: checks wrong logs
        original-url: github.com/EPAS05/loglint
        settings:
          enable_lowercase: true
          enable_english: true
          enable_special: true
          enable_sensitive: true
          sensitive_words:
            - "password"
            - "token"
            - "secret"
            - "credit"

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
